### ISSUE TITLE
Cannot read double values with ModbusClient

### ISSUE THREAD

**Issue by pFonta88** [rossmann-engineering/EasyModbusTCP.Java#7]
Good morning,

checking in the source code of ModbusClient, I found that the method named `ConvertRegistersToDouble` has a different behaviour from what its name suggests.

The first thing I expected from this method was a `double` return type, but the return type is `int`. I don't understand how to manage this value to obtain the expected `double` value.
The second strange thing is that, as `double` values are represented by 64 bits, to read the bits that composes the value I will read 4 registers from the modbus server. But the method allow only an `int[]` input with length = 2 (otherwise it throws an exception).

Reading from the online documentation here [http://easymodbustcp.net/java-modbusclient-methods](url), it seems that the correct behavior is read 2 registers and obtain an `int` as response (see the method in the list, there's an example).

Can you please explain the correct way to use this method and, if with this method isn't possible, if there's another way to use ModbusClient to read 4 registers and convert it to a `double` value?

Thanks in advance,
Regards

**Comment by Buger-od-ua** [comment]
Hello, I've met this issue while was using this lib.
Try to use ConvertRegistersToDoublePrecisionFloat( );

But there is one thing. Modbus Protocol does not specify how data ( such as doubles, longs or Strings) should be transfered. Manufacturers of devices with Modbus server on board are free to choose whatever way of "conversion" from modbus registers (which are 2byte) to 8 byte double, or ony other type which is bigger than 2 bytes.

In this case you have to understand how double value "packed" into 4 or 2 registers. You can use some online convertors or some special soft which can convert data with different byteorder. F.e. Modbus Poll serves well. After that you have to do this conversion by yourself or find online. 
Be careful with last bits, because in java int, double, long types they serve to mark "-" values. While modbus server could send you unsigned data type, which java does not support.

**Comment by pFonta88** [comment]
Hello,

thanks for your answer, using this method I'm able to read and decode `double` values.

Aboutthe fact that manufacturers of devices could use different way of registers conversion in data types bigger than2 bytes, I completely agree with you.
I manage this by adding a customizable pre-processing step between register reading that provides `int[]` and the conversion in the desired data type (in this case of `double` with the method you suggested).

Do you know why in the source code there isn't the method you suggested, that is instead accessible using the library downloaded from the website? Probably is a version problem, but the version number indicated here and in the website is the same, you found this mismatching?

**Comment by Buger-od-ua** [comment]
Actualy I don't know. Unfortunaly it is how it is :).
I use version from [SourceForge](https://sourceforge.net/projects/easymodbustcp-udp-java/files/latest/download). 2.7 as far as I understand.

**Comment by pFonta88** [comment]
I use the lastest version from SourceForge, so 2.8 (but the page isn't completely update, for instance in the Summary tab the last release note is related to the 2.7 version, but in the Files tab there is a file with version 2.8 and the date equals to the last update.
Javadocs also don't report this method. I think it's a documentation problem.

Thanks for your support
Regards
